version: '3.5'
services:
  frontend:
    environment:
      REACT_APP_API_URL: http://localhost:4000/
    image: vaibhavvt/proj-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    environment:
      MONGO_URL: mongodb+srv://vaibhavthapliyal19:naitik@cluster0.5bkzwu6.mongodb.net/?retryWrites=true&w=majority
    image: vaibhavvt/proj-backend
    ports:
      - "4000:4000"

    # depends_on:
    #   - mongodb
  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"