---
- name: Pull docker image of backend
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull front-end image
      docker_image:
        name: vaibhavvt/proj-backend:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name BackEnd vaibhavvt/proj-backend